# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SalesAgentStub(object):
    """The Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateReply = channel.unary_unary(
                '/agent.SalesAgent/GenerateReply',
                request_serializer=agent__pb2.AgentRequest.SerializeToString,
                response_deserializer=agent__pb2.AgentReply.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/agent.SalesAgent/Ping',
                request_serializer=agent__pb2.PingRequest.SerializeToString,
                response_deserializer=agent__pb2.PingReply.FromString,
                _registered_method=True)


class SalesAgentServicer(object):
    """The Service Definition
    """

    def GenerateReply(self, request, context):
        """Our primary synchronous generation method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Cheap authenticated call for the backend readiness probe (KI-083).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateReply': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReply,
                    request_deserializer=agent__pb2.AgentRequest.FromString,
                    response_serializer=agent__pb2.AgentReply.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agent__pb2.PingRequest.FromString,
                    response_serializer=agent__pb2.PingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.SalesAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.SalesAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalesAgent(object):
    """The Service Definition
    """

    @staticmethod
    def GenerateReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.SalesAgent/GenerateReply',
            agent__pb2.AgentRequest.SerializeToString,
            agent__pb2.AgentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.SalesAgent/Ping',
            agent__pb2.PingRequest.SerializeToString,
            agent__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
