# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btools.proto\x12\x05tools\"/\n\x0b\x42ookRequest\x12\x0e\n\x06leadId\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61teTime\x18\x02 \x01(\t\"3\n\x11UpdateLeadRequest\x12\x0e\n\x06leadId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"B\n\x0cToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61taJson\x18\x03 \x01(\t2\x8d\x01\n\x08\x43rmTools\x12<\n\x0f\x42ookAppointment\x12\x12.tools.BookRequest\x1a\x13.tools.ToolResponse\"\x00\x12\x43\n\x10UpdateLeadStatus\x12\x18.tools.UpdateLeadRequest\x1a\x13.tools.ToolResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=22
  _globals['_BOOKREQUEST']._serialized_end=69
  _globals['_UPDATELEADREQUEST']._serialized_start=71
  _globals['_UPDATELEADREQUEST']._serialized_end=122
  _globals['_TOOLRESPONSE']._serialized_start=124
  _globals['_TOOLRESPONSE']._serialized_end=190
  _globals['_CRMTOOLS']._serialized_start=193
  _globals['_CRMTOOLS']._serialized_end=334
# @@protoc_insertion_point(module_scope)
