# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tools_pb2 as tools__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrmToolsStub(object):
    """Python calls this, NestJS executes it!
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookAppointment = channel.unary_unary(
                '/tools.CrmTools/BookAppointment',
                request_serializer=tools__pb2.BookRequest.SerializeToString,
                response_deserializer=tools__pb2.ToolResponse.FromString,
                _registered_method=True)
        self.UpdateLeadStatus = channel.unary_unary(
                '/tools.CrmTools/UpdateLeadStatus',
                request_serializer=tools__pb2.UpdateLeadRequest.SerializeToString,
                response_deserializer=tools__pb2.ToolResponse.FromString,
                _registered_method=True)


class CrmToolsServicer(object):
    """Python calls this, NestJS executes it!
    """

    def BookAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLeadStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrmToolsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.BookAppointment,
                    request_deserializer=tools__pb2.BookRequest.FromString,
                    response_serializer=tools__pb2.ToolResponse.SerializeToString,
            ),
            'UpdateLeadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLeadStatus,
                    request_deserializer=tools__pb2.UpdateLeadRequest.FromString,
                    response_serializer=tools__pb2.ToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tools.CrmTools', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tools.CrmTools', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrmTools(object):
    """Python calls this, NestJS executes it!
    """

    @staticmethod
    def BookAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.CrmTools/BookAppointment',
            tools__pb2.BookRequest.SerializeToString,
            tools__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLeadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.CrmTools/UpdateLeadStatus',
            tools__pb2.UpdateLeadRequest.SerializeToString,
            tools__pb2.ToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
