/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export interface AcceptClinicInvitationDto {
  /**
   * Single-use clinic invitation token
   * @minLength 64
   * @maxLength 64
   */
  token: string;
  /**
   * @minLength 12
   * @maxLength 72
   */
  password?: string;
  /** @maxLength 100 */
  firstName?: string;
  /** @maxLength 100 */
  lastName?: string;
}
