/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { RecentActivityDto } from "./recentActivityDto";

export interface AnalyticsSummaryDto {
  totalLeads: number;
  activeConversations: number;
  needsAttention: number;
  aiConversionRate: number;
  recentActivity: RecentActivityDto[];
}
