/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type AuthControllerGetProfile200UserLocale =
  | (typeof AuthControllerGetProfile200UserLocale)[keyof typeof AuthControllerGetProfile200UserLocale]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthControllerGetProfile200UserLocale = {
  EN: "EN",
  TR: "TR",
  AR: "AR",
} as const;
