/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type AuthControllerRefreshTokens200User = {
  id?: string;
  firstName?: string;
  lastName?: string;
  /** @nullable */
  organizationId?: string | null;
  hasCompletedOnboarding?: boolean;
};
