/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { AuthControllerRefreshTokens200User } from "./authControllerRefreshTokens200User";

export type AuthControllerRefreshTokens200 = {
  access_token?: string;
  user?: AuthControllerRefreshTokens200User;
};
