/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { AuthControllerGetProfile200UserLocale } from "./authControllerGetProfile200UserLocale";

export type AuthControllerGetProfile200User = {
  id: string;
  /** @nullable */
  locale: AuthControllerGetProfile200UserLocale;
};
