/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ConversationsControllerGetConversations200ItemLead } from "./conversationsControllerGetConversations200ItemLead";
import type { ConversationsControllerGetConversations200ItemMessagesItem } from "./conversationsControllerGetConversations200ItemMessagesItem";

export type ConversationsControllerGetConversations200Item = {
  id?: string;
  updatedAt?: string;
  /** @nullable */
  lead?: ConversationsControllerGetConversations200ItemLead;
  messages?: ConversationsControllerGetConversations200ItemMessagesItem[];
};
