/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * JSON payload containing business rules for the AI
 */
export type CreateOrganizationDtoBusinessRules = { [key: string]: unknown };
