/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateLeadDtoSocialLinks } from "./createLeadDtoSocialLinks";
import type { CreateLeadDtoGender } from "./createLeadDtoGender";
import type { CreateLeadDtoStatus } from "./createLeadDtoStatus";
import type { CreateLeadDtoPriority } from "./createLeadDtoPriority";
import type { CreateLeadDtoCurrency } from "./createLeadDtoCurrency";

export interface CreateLeadDto {
  firstName: string;
  lastName: string;
  phoneNumber: string;
  country: string;
  timezone: string;
  primaryLanguage: string;
  preferredLanguage?: string;
  nativeName?: string;
  email?: string;
  socialLinks?: CreateLeadDtoSocialLinks;
  gender?: CreateLeadDtoGender;
  sourceId?: string;
  pipelineStageId?: string;
  assignedAgentId?: string;
  status?: CreateLeadDtoStatus;
  priority?: CreateLeadDtoPriority;
  estimatedValue?: number;
  currency?: CreateLeadDtoCurrency;
  expectedServiceDate?: string;
  nextFollowUpAt?: string;
}
