/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateChannelDtoProvider } from "./createChannelDtoProvider";

export interface CreateChannelDto {
  provider: CreateChannelDtoProvider;
  /** The Account ID for the provider (e.g., WhatsApp Phone Number ID) */
  providerAccountId: string;
  /** The Access Token or Secret for the provider */
  accessToken: string;
}
