/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export interface InboxMessageDto {
  id: string;
  conversationId: string;
  /** @nullable */
  senderId: string | null;
  content: string;
  /** @nullable */
  mediaUrl: string | null;
  type: string;
  handledBy: string;
  /** Delivery/processing state. UNKNOWN is preserved from the outbound attempt. */
  status: string;
  createdAt: string;
  updatedAt: string;
}
