/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LeadResponseDto } from "./leadResponseDto";
import type { LeadsPaginatedResponseDtoMeta } from "./leadsPaginatedResponseDtoMeta";

export interface LeadsPaginatedResponseDto {
  data: LeadResponseDto[];
  meta: LeadsPaginatedResponseDtoMeta;
}
