/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LeadsControllerFindAllStatus } from "./leadsControllerFindAllStatus";
import type { LeadsControllerFindAllPriority } from "./leadsControllerFindAllPriority";

export type LeadsControllerFindAllParams = {
  page?: number;
  /**
   * @maximum 100
   */
  limit?: number;
  /**
   * A JSON-stringified AST for filtering with AND/OR logic and dynamic operators.
   */
  filters?: string;
  /**
   * A JSON-stringified array of sort nodes.
   */
  sorts?: string;
  status?: LeadsControllerFindAllStatus;
  priority?: LeadsControllerFindAllPriority;
};
