/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ManualMessageResponseDtoDeliveryStatus } from "./manualMessageResponseDtoDeliveryStatus";

export interface ManualMessageResponseDto {
  id: string;
  conversationId: string;
  /** @nullable */
  senderId: string | null;
  content: string;
  /** @nullable */
  mediaUrl: string | null;
  type: string;
  handledBy: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  /** SENT, UNKNOWN (check WhatsApp before resending) or FAILED */
  deliveryStatus: ManualMessageResponseDtoDeliveryStatus;
  /** Non-blocking notices for staff, e.g. PATIENT_OPTED_OUT (the patient sent STOP; the message was still sent). Empty otherwise. */
  warnings: string[];
}
