/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type NotificationsControllerGetNotifications200Item = {
  id?: string;
  organizationId?: string;
  userId?: string;
  type?: string;
  title?: string;
  body?: string;
  isRead?: boolean;
  /** @nullable */
  referenceId?: string | null;
  /** @nullable */
  referenceType?: string | null;
  createdAt?: string;
  updatedAt?: string;
};
