/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export interface PlatformClinicDto {
  id: string;
  name: string;
  createdAt: string;
  isActive: boolean;
  memberCount: number;
  ownerEmails: string[];
}
