/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Optional: Map this stage to a core AI state.
 */
export type UpdatePipelineStageDtoMappedStatus =
  (typeof UpdatePipelineStageDtoMappedStatus)[keyof typeof UpdatePipelineStageDtoMappedStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePipelineStageDtoMappedStatus = {
  NEW: "NEW",
  QUALIFYING: "QUALIFYING",
  QUALIFIED: "QUALIFIED",
  READY_TO_BOOK: "READY_TO_BOOK",
  READY_TO_PAY: "READY_TO_PAY",
  HANDED_OFF: "HANDED_OFF",
  UNQUALIFIED: "UNQUALIFIED",
  WON: "WON",
  LOST: "LOST",
} as const;
