/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UserLocale } from "./userLocale";

export interface UpdateUserProfileDto {
  /** @maxLength 100 */
  firstName?: string;
  /** @maxLength 100 */
  lastName?: string;
  /** E.164 phone or empty string */
  phoneNumber?: string;
  /** E.164 phone or empty string */
  whatsappNumber?: string;
  /** @maxItems 20 */
  spokenLanguages?: string[];
  locale?: UserLocale;
}
