/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type UpdateLeadDtoGender =
  (typeof UpdateLeadDtoGender)[keyof typeof UpdateLeadDtoGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateLeadDtoGender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  OTHER: "OTHER",
  UNKNOWN: "UNKNOWN",
} as const;
