/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateLeadStageDtoStatus } from "./updateLeadStageDtoStatus";

export interface UpdateLeadStageDto {
  /** The UUID of the pipeline stage to move the lead to */
  pipelineStageId: string;
  /** Optional status update when moving stage */
  status?: UpdateLeadStageDtoStatus;
}
