/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UserProfileDtoLocale } from "./userProfileDtoLocale";
import type { ProfileMembershipDto } from "./profileMembershipDto";

export interface UserProfileDto {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  /** @nullable */
  phoneNumber: string | null;
  /** @nullable */
  whatsappNumber: string | null;
  spokenLanguages: string[];
  /** @nullable */
  locale: UserProfileDtoLocale;
  memberships: ProfileMembershipDto[];
}
