/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type WebhooksControllerVerifyWebhookParams = {
  "hub.mode": string;
  "hub.verify_token": string;
  "hub.challenge": string;
};
