/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ClinicFactsDto } from "./clinicFactsDto";

export interface ClinicFactRevisionDto {
  version: number;
  facts: ClinicFactsDto;
  /** @nullable */
  approvedAt: string | null;
  /** @nullable */
  approvedBy: string | null;
}
