/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ClinicFactRevisionDto } from "./clinicFactRevisionDto";

/**
 * @nullable
 */
export type ClinicFactSheetDtoLatest = ClinicFactRevisionDto | null;
