/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { ClinicTreatmentDtoCurrency } from "./clinicTreatmentDtoCurrency";

export interface ClinicTreatmentDto {
  name: string;
  priceMin: number;
  priceMax: number;
  currency: ClinicTreatmentDtoCurrency;
  unit: string;
  included: string;
}
