/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type ConversationsControllerGetConversationsFilter =
  (typeof ConversationsControllerGetConversationsFilter)[keyof typeof ConversationsControllerGetConversationsFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationsControllerGetConversationsFilter = {
  all: "all",
  needs_reply: "needs_reply",
  handed_off: "handed_off",
  ai_active: "ai_active",
  mine: "mine",
  unassigned: "unassigned",
} as const;
