/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type CreateChannelDtoProvider =
  (typeof CreateChannelDtoProvider)[keyof typeof CreateChannelDtoProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateChannelDtoProvider = {
  WHATSAPP_CLOUD_API: "WHATSAPP_CLOUD_API",
  INSTAGRAM_GRAPH_API: "INSTAGRAM_GRAPH_API",
} as const;
