/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type CreateLeadDtoPriority =
  (typeof CreateLeadDtoPriority)[keyof typeof CreateLeadDtoPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLeadDtoPriority = {
  HOT: "HOT",
  WARM: "WARM",
  COLD: "COLD",
} as const;
