/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Safe message origin; raw provider metadata is never exposed
 */
export type InboxMessageDtoOrigin =
  (typeof InboxMessageDtoOrigin)[keyof typeof InboxMessageDtoOrigin];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InboxMessageDtoOrigin = {
  WHATSAPP_PHONE: "WHATSAPP_PHONE",
  WHATSAPP_HISTORY: "WHATSAPP_HISTORY",
} as const;
