/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export interface IssueClinicInvitationDto {
  /** Email address of the staff to invite */
  email: string;
  /** Role ID to grant upon acceptance */
  roleId: string;
}
