/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type LeadResponseDtoCurrency =
  (typeof LeadResponseDtoCurrency)[keyof typeof LeadResponseDtoCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadResponseDtoCurrency = {
  USD: "USD",
  TRY: "TRY",
  EUR: "EUR",
  GBP: "GBP",
} as const;
