/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LeadsControllerFindAllStatus } from "./leadsControllerFindAllStatus";
import type { LeadsControllerFindAllPriority } from "./leadsControllerFindAllPriority";

export type LeadsControllerFindAllParams = {
  /**
   * Page number (default: 1)
   */
  page?: number;
  /**
   * Items per page, max 100 (default: 20)
   * @maximum 100
   */
  limit?: number;
  /**
   * JSON AST filter array
   */
  filters?: string;
  /**
   * JSON AST sort array
   */
  sorts?: string;
  status?: LeadsControllerFindAllStatus;
  priority?: LeadsControllerFindAllPriority;
};
