/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type LeadResponseDtoPriority =
  (typeof LeadResponseDtoPriority)[keyof typeof LeadResponseDtoPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadResponseDtoPriority = {
  HOT: "HOT",
  WARM: "WARM",
  COLD: "COLD",
} as const;
