/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** The email address of the user */
  email: string;
  /** The user password (min 6 characters) */
  password: string;
  /** The target organization to select (for multi-tenant users) */
  organizationId?: string;
}
