/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * SENT, UNKNOWN (check WhatsApp before resending) or FAILED
 */
export type ManualMessageResponseDtoDeliveryStatus =
  (typeof ManualMessageResponseDtoDeliveryStatus)[keyof typeof ManualMessageResponseDtoDeliveryStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManualMessageResponseDtoDeliveryStatus = {
  SENT: "SENT",
  UNKNOWN: "UNKNOWN",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
} as const;
