/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type OrganizationsControllerCreateOrganization201 = {
  message: string;
  organizationId: string;
  access_token: string;
};
