/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateLeadDtoSocialLinks } from "./updateLeadDtoSocialLinks";
import type { UpdateLeadDtoGender } from "./updateLeadDtoGender";
import type { UpdateLeadDtoStatus } from "./updateLeadDtoStatus";
import type { UpdateLeadDtoPriority } from "./updateLeadDtoPriority";
import type { UpdateLeadDtoCurrency } from "./updateLeadDtoCurrency";

export interface UpdateLeadDto {
  firstName?: string;
  lastName?: string;
  phoneNumber?: string;
  country?: string;
  timezone?: string;
  primaryLanguage?: string;
  preferredLanguage?: string;
  nativeName?: string;
  email?: string;
  socialLinks?: UpdateLeadDtoSocialLinks;
  gender?: UpdateLeadDtoGender;
  sourceId?: string;
  pipelineStageId?: string;
  assignedAgentId?: string;
  status?: UpdateLeadDtoStatus;
  priority?: UpdateLeadDtoPriority;
  estimatedValue?: number;
  currency?: UpdateLeadDtoCurrency;
  expectedServiceDate?: string;
  nextFollowUpAt?: string;
}
