/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export interface WeeklyActivityDto {
  /** @minimum 0 */
  aiReplies: number;
  /** @minimum 0 */
  staffDashboardReplies: number;
  /** @minimum 0 */
  staffPhoneMessages: number;
  /** @minimum 0 */
  denominator: number;
  /** @nullable */
  aiPercent: number | null;
  /** @nullable */
  staffPercent: number | null;
}
