/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type WeeklyConsultationsDtoValue =
  | (typeof WeeklyConsultationsDtoValue)[keyof typeof WeeklyConsultationsDtoValue]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyConsultationsDtoValue = {} as const;
