/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export interface WeeklyCoverageDto {
  /** @minimum 0 */
  legacyOriginMessages: number;
  /** @minimum 0 */
  unresolvedHandoffReferences: number;
  /** @minimum 0 */
  topicClassifiedConversations: number;
  /** @minimum 0 */
  topicUnclassifiedConversations: number;
  /** @minimum 0 */
  excludedPhoneMessages: number;
}
