/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type WeeklyReportDtoVersion =
  (typeof WeeklyReportDtoVersion)[keyof typeof WeeklyReportDtoVersion];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyReportDtoVersion = {
  NUMBER_1: 1,
} as const;
