/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type WeeklyConsultationsDtoReason =
  (typeof WeeklyConsultationsDtoReason)[keyof typeof WeeklyConsultationsDtoReason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyConsultationsDtoReason = {
  consultation_records_unavailable: "consultation_records_unavailable",
} as const;
