/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { WeeklyPeriodDtoTimezone } from "./weeklyPeriodDtoTimezone";

export interface WeeklyPeriodDto {
  weekStart: string;
  weekEnd: string;
  startUtc: string;
  endUtc: string;
  cutoffUtc: string;
  timezone: WeeklyPeriodDtoTimezone;
  inProgress: boolean;
}
