/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { WeeklySenderIntervalDto } from "./weeklySenderIntervalDto";

export interface WeeklyReplyIntervalDto {
  /** @minimum 0 */
  opportunities: number;
  /** @minimum 0 */
  replied: number;
  /** @minimum 0 */
  pending: number;
  /** @nullable */
  medianSeconds: number | null;
  /** @nullable */
  p90Seconds: number | null;
  ai: WeeklySenderIntervalDto;
  staff: WeeklySenderIntervalDto;
}
