/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { WeeklyReportDtoVersion } from "./weeklyReportDtoVersion";
import type { WeeklyPeriodDto } from "./weeklyPeriodDto";
import type { WeeklyActivityDto } from "./weeklyActivityDto";
import type { WeeklyReplyIntervalDto } from "./weeklyReplyIntervalDto";
import type { WeeklyConsultationsDto } from "./weeklyConsultationsDto";
import type { WeeklyTopicDto } from "./weeklyTopicDto";
import type { WeeklyCoverageDto } from "./weeklyCoverageDto";
import type { WeeklyReportDtoMethodologyItem } from "./weeklyReportDtoMethodologyItem";

export interface WeeklyReportDto {
  version: WeeklyReportDtoVersion;
  period: WeeklyPeriodDto;
  generatedAt: string;
  asOf: string;
  /** @minimum 0 */
  newLeads: number;
  /** @minimum 0 */
  activeConversations: number;
  /** @minimum 0 */
  patientMessages: number;
  activity: WeeklyActivityDto;
  replyInterval: WeeklyReplyIntervalDto;
  /** @minimum 0 */
  handedToTeamConversations: number;
  consultations: WeeklyConsultationsDto;
  topics: WeeklyTopicDto[];
  coverage: WeeklyCoverageDto;
  methodology: WeeklyReportDtoMethodologyItem[];
}
