/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type WeeklyPeriodDtoTimezone =
  (typeof WeeklyPeriodDtoTimezone)[keyof typeof WeeklyPeriodDtoTimezone];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyPeriodDtoTimezone = {
  "Europe/Istanbul": "Europe/Istanbul",
} as const;
