/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type WeeklyReportDtoMethodologyItem =
  (typeof WeeklyReportDtoMethodologyItem)[keyof typeof WeeklyReportDtoMethodologyItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyReportDtoMethodologyItem = {
  surviving_records: "surviving_records",
  all_recorded_activity: "all_recorded_activity",
  legacy_origin: "legacy_origin",
  provider_acceptance: "provider_acceptance",
  reply_interval: "reply_interval",
  phone_excluded: "phone_excluded",
  handoff_retention: "handoff_retention",
  approximate_topics: "approximate_topics",
  consultations_unavailable: "consultations_unavailable",
} as const;
