/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */

export type WeeklyTopicDtoId =
  (typeof WeeklyTopicDtoId)[keyof typeof WeeklyTopicDtoId];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyTopicDtoId = {
  price: "price",
  implants: "implants",
  crowns_veneers: "crowns_veneers",
  consultation: "consultation",
  travel_location: "travel_location",
  payment: "payment",
  other: "other",
} as const;
