/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Lean Commerce API
 * The AI Sales Agent CRM API Documentation
 * OpenAPI spec version: 1.0
 */
import type { WeeklyConsultationsDtoValue } from "./weeklyConsultationsDtoValue";
import type { WeeklyConsultationsDtoAvailability } from "./weeklyConsultationsDtoAvailability";
import type { WeeklyConsultationsDtoReason } from "./weeklyConsultationsDtoReason";

export interface WeeklyConsultationsDto {
  /** @nullable */
  value: WeeklyConsultationsDtoValue;
  availability: WeeklyConsultationsDtoAvailability;
  reason: WeeklyConsultationsDtoReason;
}
